### PR TITLE
Added support for composite primary keys as `id`

### PR DESCRIPTION
**Pull request by dekelev**
When using DB tables with composite primary keys, there is no way to use the `id` argument to match or fail against a single unique record.

This PR adds support for composite primary keys by enabling a developer to set the `service.id` property to an array of strings and use the `id` argument to pass all composite keys' values of a record.

When calling a service method with the `id` argument, all primary keys are required to be passed if using composite primary keys.

Composite `id` values can be passed as:

- string with values separated by the new `service.idSeparator` property or using the default comma separator (order matter, recommended for REST)
- JSON array (order matter, recommended for internal service calls)
- JSON object (more readable, recommended for internal service calls)

### CODE REVIEW

**Comment by mcchrish** [comment]
@dekelev thanks for contributing! Sorry for the late reply. I don't have much free time on maintaining this lib. But feel free to use your own fork for the mean time.

Taking a quick look, this looks nice to add. I'm wondering if this can also be worked around by having a new primary key for table as an intermediate for the two keys.

**Comment by dekelev** [comment]
@mcchrish I'm not sure that having a separate primary key can achieve the same results.

I think that the most important thing about this feature is to be able to query or update a record by its composite `id` and still get the exact same behavior, as it would be if the record had only a single `id` field.

**Comment by dekelev** [comment]
@mcchrish This library is not maintained and lack basic support for a lot of rudimentary stuff.
If you can please add me as a contributor, it would help to keep this alive. otherwise, I'll have to publish another package in NPM very soon.

**Comment by mcchrish** [comment]
@dekelev I apologize for the lack of maintenance of this library on my part as I struggle to find time for it. I'm happy to add you as contributor to this project, as a person who is much closer to the much needed support than I am. And also thanks so much for volunteering to be a contributor, I trust the community will keep this library alive.

Again, sorry for the lack of response and maintenance of this project.

**Pull request closed without merging**
