### PR TITLE
Add support for $and

### PR DESCRIPTION
**Pull request by vonagam**
Same functionality (and code) as in feathers-knex - https://github.com/feathersjs-ecosystem/feathers-knex/pull/163

### CODE REVIEW

**Comment by mcchrish** [comment]
Hi @vonagam thanks so much for contributing. Can we also port the documentation and test from knex? I assume it wouldn't be so hard as it works almost the same way.

**Comment by vonagam** [comment]
Added test for `$and`.

But i see no documentation for `$like`, so i assume that this reference to knex service docs from readme  - `It works almost the same as the Knex service adapter` - is enough, no?

Also did small refactor. Nothing has changed, just moved up handling of `$select` and some lines became unnecessary.

**Comment by mcchrish** [comment]
Awesome @vonagam thanks for that! Build error in the CI seems unrelated. Seems like some old dependencies doesn't exists anymore.

**Comment by mcchrish** [comment]
@vonagam I've published 0.9.0 with these change and also including some maintenance changes.

**Pull request merged**
